# Generated by Django 2.1.7 on 2019-03-22 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Ac_Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen_Table',
            fields=[
                ('citz_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=100)),
                ('address', models.TextField()),
                ('gender', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('otp', models.CharField(default=False, max_length=20)),
                ('status', models.CharField(default=False, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint_Table',
            fields=[
                ('comp_id', models.AutoField(primary_key=True, serialize=False)),
                ('cmp_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(max_length=20, null=True)),
                ('message', models.TextField()),
                ('image', models.ImageField(default=False, upload_to='complaints')),
                ('close_date', models.DateField(null=True)),
                ('citz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ac_Citizen.Citizen_Table')),
                ('dept_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ac_Admin.Department_Table')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback_Table',
            fields=[
                ('feed_id', models.AutoField(primary_key=True, serialize=False)),
                ('feed_date', models.DateField(auto_now_add=True)),
                ('feed_message', models.TextField()),
                ('image', models.ImageField(default=False, upload_to='feedbacks')),
                ('citz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ac_Citizen.Citizen_Table')),
                ('dept_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ac_Admin.Department_Table')),
            ],
        ),
        migrations.CreateModel(
            name='Reject_Table',
            fields=[
                ('reject_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('rej_date', models.DateField(auto_now_add=True)),
                ('citz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ac_Citizen.Citizen_Table')),
            ],
        ),
        migrations.CreateModel(
            name='Reply_Table',
            fields=[
                ('reply_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('rep_date', models.DateField(auto_now_add=True)),
                ('feed_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ac_Citizen.Feedback_Table')),
            ],
        ),
    ]
