# Generated by Django 2.1.7 on 2019-03-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Table',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Contact_Us',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Department_Table',
            fields=[
                ('dept_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
    ]
