# Generated by Django 2.1.7 on 2019-03-22 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Ac_Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article_Table',
            fields=[
                ('art_id', models.AutoField(primary_key=True, serialize=False)),
                ('art_date', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('approve', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NGOS_Table',
            fields=[
                ('ngo_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=100)),
                ('address', models.CharField(max_length=1000)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion_Table',
            fields=[
                ('sugs_id', models.AutoField(primary_key=True, serialize=False)),
                ('sug_date', models.DateField(auto_now_add=True)),
                ('message', models.TextField()),
                ('dept_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ac_Admin.Department_Table')),
            ],
        ),
        migrations.AddField(
            model_name='article_table',
            name='ngo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ac_Ngo.NGOS_Table'),
        ),
    ]
