# Generated by Django 2.1.7 on 2019-03-22 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ac_Officer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer_table',
            name='otp',
            field=models.CharField(default=False, max_length=10),
        ),
        migrations.AddField(
            model_name='officer_table',
            name='status',
            field=models.CharField(default=False, max_length=20),
        ),
    ]
